version: "3.9"

services:
  proxy:
    image: nginx
    container_name: jtm_proxy 
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - certbot
      - web
      - db
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /var/certbot/conf:/etc/letsencrypt
      - /var/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: jtm_ssl
    volumes:
      - /var/certbot/conf:/etc/letsencrypt
      - /var/certbot/www:/var/www/certbot
  web:
    image: j0suetm/web
    container_name: jtm_web
    networks:
      - frontend
      - backend
    depends_on:
      - svc
  svc:
    image: j0suetm/svc
    container_name: jtm_svc
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: jtm_db
    networks:
      - backend
    restart: always
    env_file: .env
    volumes:
      - /var/db:/data/db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local
